# Generated by Django 5.2.5 on 2025-08-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, help_text='Укажите telegram chat-id', max_length=50, null=True, verbose_name='telegram chat id'),
        ),
    ]
