# Generated by Django 5.2.5 on 2025-08-25 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Укажите место, в котором необходимо выполнять привычку', max_length=100)),
                ('time', models.TimeField(help_text='Укажите время, когда необходимо выполнять привычку')),
                ('action', models.CharField(help_text='Укажите действие, которое представляет собой привычка', max_length=100)),
                ('is_pleasant', models.BooleanField(default=False, help_text='Привычка, которую можно привязать к выполнению полезной привычки.')),
                ('frequency', models.PositiveSmallIntegerField(default=1, help_text='Периодичность выполнения привычки для напоминания в днях.')),
                ('reward', models.CharField(blank=True, help_text='Вознаграждение после выполнения привычки.', max_length=100, null=True)),
                ('duration', models.PositiveIntegerField(help_text='Время, которое предположительно потратит пользователь на выполнение привычки в секундах.')),
                ('is_public', models.BooleanField(default=False)),
                ('related_habit', models.ForeignKey(blank=True, help_text='Привычка, которая связана с другой полезной привычкой', limit_choices_to={'is_pleasant': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
